feat: Add ut to all helper functions
apollodao/cw-dex pull request #66
Opened 2022-11-16 17:04 UTC by apollo-pablo

Closes #54 

> Problem

We dont have any test on math functions.

> Tasks

- [x] Add UT to implementations Helpers functions.
- [x] Add on every file instead of new files.

> Notes

Format and lints failures are from develop branch, we should make a PR and fix them first.

2022-11-17 14:52 UTC, apollo-pacman reviewed
nice work! 👍 a few comments @apollo-pablo

2022-11-17 14:52 UTC, apollo-pacman commented on src/implementations/astroport/helpers.rs
> +            };
why did we need to make this change?

2022-11-21 11:16 UTC, apollo-sturdy requested changes

2022-11-21 11:16 UTC, apollo-sturdy commented on src/implementations/junoswap/helpers.rs
> +    // }
Remove unused code.

2022-11-21 11:16 UTC, apollo-sturdy commented on src/implementations/astroport/helpers.rs
> +                    }
Why add extra spacing? Pls use rustfmt.

2022-11-21 11:16 UTC, apollo-sturdy commented on src/implementations/junoswap/helpers.rs
> +/// This function does not take into account protocol_fee_percent and lp_fee_percent
Neither does Junoswap, so why mention it? Please remove comment.

2022-11-21 11:16 UTC, apollo-sturdy commented on src/implementations/junoswap/helpers.rs
> +/// - token2.amount > 0
Not sure what this means. Can you please either remove this or explain it further so its understandable?

2022-11-21 11:16 UTC, apollo-sturdy commented on src/implementations/junoswap/helpers.rs
> +            lp_token_supply: usdc.amount + dai.amount, // should this be reserve_a+reserve_b?
Shouldn't matter what this value is. Remove comment.

2022-11-21 11:16 UTC, apollo-sturdy commented on src/implementations/junoswap/helpers.rs
> +    fn juno_simulate_provide_liquidity_test(
Some of these tests fail. Please fix before request review.

2023-02-13 21:33 UTC, closed without merging